### ISSUE TITLE
How to scan mirrored QR codes

### ISSUE THREAD

**Issue by mskumara** [googlesamples/android-vision#76] opened 2016-03-11 10:23 UTC
i have some qr codes that have mirrored on printing.. how can i scan them with android vision api..

**Comment by pchx** [comment] 2016-03-11 15:09
Right now, the barcode API can't read mirrored QR codes. We're working on this for a future release.

**Comment by Nom4d3** [comment] 2016-05-06 13:43
This would also solve #62.
It would be great to have this feature. To keep things working nicely, without any other libraries, I'm using the camera with Negative effect.

**Comment by didbarbosa** [comment] 2016-10-20 14:19
Hello, any news on this?

I have this issue while scanning from a FRONT camera. It detects no barcode, but if I print the barcode horizontally flipped, it is well detected.
Device is a Lenovo Tab A7-10, with **FRONT** camera only. BTW, Camera.getCameraInfo() returns Camera.CameraInfo.**CAMERA_FACING_BACK**

Thanks.

**Comment by pchx** [comment] 2016-12-06 19:28
Duplicate of #66, which is now fixed. The latest version of our Barcode API (part of [Google Play Services 10.0](https://developers.google.com/vision/release-notes#google_play_services_100)) adds support for mirrored QR codes.

**Closed by pchx** 2016-12-06 19:28 UTC
Labels: Barcode
