### ISSUE TITLE
Barcode detection is crashing at version 15.0.2

### ISSUE THREAD

**Issue by elapouya** [googlesamples/android-vision#388] opened 2018-09-24 14:46 UTC
I integrated barcode-reader google sample in my app : 

https://github.com/googlesamples/android-vision/tree/master/visionSamples/barcode-reader

But it crashes randomly : it can work for several minutes or only a few seconds.
It noticed it appends mainly when reading small barcode / qrcode.

The crash dump :

```
--------- beginning of crash
09-24 15:16:56.072 15926 16058 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 16058 (Thread-4)
09-24 15:16:56.243 16155 16155 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-24 15:16:56.244 16155 16155 F DEBUG   : Build fingerprint: 'samsung/greatltexx/greatlte:8.0.0/R16NW/N950FXXU5CRHA:user/release-keys'
09-24 15:16:56.244 16155 16155 F DEBUG   : Revision: '9'
09-24 15:16:56.244 16155 16155 F DEBUG   : ABI: 'arm64'
09-24 15:16:56.244 16155 16155 F DEBUG   : pid: 15926, tid: 16058, name: Thread-4  >>> info.mylastname.dcinventory <<<
09-24 15:16:56.244 16155 16155 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc
09-24 15:16:56.244 16155 16155 F DEBUG   : Cause: null pointer dereference
09-24 15:16:56.244 16155 16155 F DEBUG   :     x0   0000000000000000  x1   000000790b0f1c20  x2   1fc0000000000000  x3   0000000000000003
09-24 15:16:56.244 16155 16155 F DEBUG   :     x4   0000000000000000  x5   0000007919820468  x6   0000000000000000  x7   0000000004d8c0ee
09-24 15:16:56.244 16155 16155 F DEBUG   :     x8   19adc24c947c1e60  x9   19adc24c947c1e60  x10  0000000000000002  x11  0000007918a502b0
09-24 15:16:56.244 16155 16155 F DEBUG   :     x12  fffffffffffe0000  x13  ffffffffa45a9ff1  x14  000000000dbcb7bf  x15  000000793d278000
09-24 15:16:56.244 16155 16155 F DEBUG   :     x16  000000793d26dcb0  x17  000000793d20a740  x18  0000000000000000  x19  00000078f7109c18
09-24 15:16:56.244 16155 16155 F DEBUG   :     x20  00000078f7109c00  x21  00000078f7109da0  x22  0000000000000001  x23  0000000000000000
09-24 15:16:56.244 16155 16155 F DEBUG   :     x24  0000000000000000  x25  0000000044870000  x26  0000000044620000  x27  0000000043240000
09-24 15:16:56.244 16155 16155 F DEBUG   :     x28  0000000044608000  x29  00000078f710a878  x30  000000790e73bf3c
09-24 15:16:56.244 16155 16155 F DEBUG   :     sp   00000078f7109b50  pc   000000790e73bf44  pstate 0000000060000000
09-24 15:16:56.251 16155 16155 F DEBUG   :
09-24 15:16:56.251 16155 16155 F DEBUG   : backtrace:
09-24 15:16:56.252 16155 16155 F DEBUG   :     #00 pc 000000000001bf44  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
09-24 15:16:56.252 16155 16155 F DEBUG   :     #01 pc 0000000000011160  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
09-24 15:16:56.252 16155 16155 F DEBUG   :     #02 pc 0000000000005bd0  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
09-24 15:16:56.252 16155 16155 F DEBUG   :     #03 pc 0000000000007674  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
09-24 15:16:56.252 16155 16155 F DEBUG   :     #04 pc 0000000000003624  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
09-24 15:16:56.252 16155 16155 F DEBUG   :     #05 pc 0000000000004c8c  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
09-24 15:16:56.252 16155 16155 F DEBUG   :     #06 pc 000000000000b758  /data/user_de/0/com.google.android.gms/app_chimera/m/0000006a/oat/arm64/DynamiteModulesA.odex (offset 0x8000)
```
The build.gradle : 

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "info.mylastname.dcinventory"
        minSdkVersion 22
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.android.gms:play-services-vision:15.0.2'
    implementation 'com.android.support:design:27.1.1'
}

```
Could you help me ?

**Comment by pchx** [comment] 2018-09-25 14:50
Duplicate of #351.

**Closed by pchx** 2018-09-25 14:50 UTC
