### ISSUE TITLE
native crash while scanning malformed PDF417 barcode

### ISSUE THREAD

**Issue by yma44** [googlesamples/android-vision#404] opened 2019-01-29 01:20 UTC
Hi,
I am getting the app crash while scanning malformed PDF417. It happens on all android (tried on android 9,8,7,6 and 5).  the crash happens not every time but normally once in 5 times scanning this barcode.

> 01-29 10:16:52.078  4976  5225 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 5225 (Thread-33), pid 4976 ({package id})
01-29 10:16:52.147  5259  5259 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-29 10:16:52.147  5259  5259 F DEBUG   : Build fingerprint: 'HUAWEI/INE-LX2/HWINE:8.1.0/HUAWEIINE-LX2/112(C706):user/release-keys'
01-29 10:16:52.147  5259  5259 F DEBUG   : Revision: '0'
01-29 10:16:52.147  5259  5259 F DEBUG   : ABI: 'arm'
01-29 10:16:52.147  5259  5259 F DEBUG   : pid: 4976, tid: 5225, name: Thread-33  >>> {package id} <<<
01-29 10:16:52.148  5259  5259 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc
01-29 10:16:52.148  5259  5259 F DEBUG   : Cause: null pointer dereference
01-29 10:16:52.148  5259  5259 F DEBUG   :     r0 ac2b26a8  r1 1028f6dc  r2 ac2b2658  r3 00000000
01-29 10:16:52.148  5259  5259 F DEBUG   :     r4 00000000  r5 ac2b2658  r6 a0a42890  r7 a0a429a4
01-29 10:16:52.148  5259  5259 F DEBUG   :     r8 00000075  r9 00000001  sl 43bb0000  fp 440a4000
01-29 10:16:52.148  5259  5259 F DEBUG   :     ip f122ad58  sp a0a42880  lr f1201d3d  pc b35d2c12  cpsr 200d0030
01-29 10:16:52.150  5259  5259 F DEBUG   : 
01-29 10:16:52.150  5259  5259 F DEBUG   : backtrace:
01-29 10:16:52.150  5259  5259 F DEBUG   :     #00 pc 00011c12  /data/data/com.google.android.gms/app_vision/barcode/libs/armeabi-v7a/libbarhopper.so
01-29 10:16:52.150  5259  5259 F DEBUG   :     #01 pc 0000a2ef  /data/data/com.google.android.gms/app_vision/barcode/libs/armeabi-v7a/libbarhopper.so
01-29 10:16:52.150  5259  5259 F DEBUG   :     #02 pc 00003333  /data/data/com.google.android.gms/app_vision/barcode/libs/armeabi-v7a/libbarhopper.so
01-29 10:16:52.150  5259  5259 F DEBUG   :     #03 pc 000043df  /data/data/com.google.android.gms/app_vision/barcode/libs/armeabi-v7a/libbarhopper.so
01-29 10:16:52.150  5259  5259 F DEBUG   :     #04 pc 00001e63  /data/data/com.google.android.gms/app_vision/barcode/libs/armeabi-v7a/libbarhopper.so
01-29 10:16:52.150  5259  5259 F DEBUG   :     #05 pc 00002a91  /data/data/com.google.android.gms/app_vision/barcode/libs/armeabi-v7a/libbarhopper.so
01-29 10:16:52.150  5259  5259 F DEBUG   :     #06 pc 00413679  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
01-29 10:16:52.150  5259  5259 F DEBUG   :     #07 pc 00075893  /dev/ashmem/dalvik-jit-code-cache (deleted)

I have tried some other app from play store which uses google vision, and it crashed with the same error as well.  The PDF417 barcode which made the native crash is this.
![capture2](https://user-images.githubusercontent.com/6530686/51877144-f6f58a00-23cf-11e9-9476-46f91b813032.PNG)
 
Thanks in advance.

**Comment by pchx** [comment] 2019-01-29 16:04
Duplicate of #351.

**Closed by pchx** 2019-01-29 16:04 UTC
Labels: Barcode
