### ISSUE TITLE
Bug: barcode and face detectors temporarily disabled for new users

### ISSUE THREAD

**Issue by pm0733464** [googlesamples/android-vision#98] opened 2016-05-19 04:38 UTC
- A service required by Mobile Vision is now disabled due to a serious bug in that service. This will prevent users who have not already used face or barcode detection from using those features. We do not recommend adding new Mobile Vision features to your app until this issue is fixed.

- For apps that already use Mobile Vision features, check [FaceDetector.isOperational()](https://developers.google.com/android/reference/com/google/android/gms/vision/face/FaceDetector.html#isOperational()) or [BarcodeDetector.isOperational()](https://developers.google.com/android/reference/com/google/android/gms/vision/barcode/BarcodeDetector.html#isOperational()) to confirm detector readiness before using the face or barcode detector.

- We are working to deploy a solution as soon as possible. We expect it will take several weeks to test it thoroughly.

**Comment by shivasurya** [comment] 2016-05-19 08:15
hello,
i'm new to mobile vision API - i'm going to adding this feature to my app and whether the barcode service is down or shall i proceed ? or any ETA 's ?

**Comment by pm0733464** [comment] 2016-05-19 14:13
I would advise holding off on adding mobile vision features to your app until we deploy a fix.  

Although face and barcode functionality will still be available to users who already have installed apps that use mobile vision, new users of your app who have not previously installed such an app will not be able to use mobile vision functionality until a fix is deployed.

**Comment by betri28** [comment] 2016-05-20 05:47
Can you give the **time** when android vision is available for new users?
Thanks

**Comment by pm0733464** [comment] 2016-05-20 19:34
I'm sorry, but we do not have a time that we can announce right now.  We are hard at work to correct this issue as soon as possible, and take this very seriously.

We will post an update to this issue thread when the solution is available.

Sorry for the inconvenience.

**Comment by vietnt134** [comment] 2016-05-21 02:15
Why you've just released an unstable version like this, you disable a very big feature and just do not know when to enable it...at least you should mark the release as alpha or review....you guy are suck :(

**Comment by betri28** [comment] 2016-05-21 11:13
Do you have any solution to disable the part cause this bug in server and open another part to new users? Try this first please!!! Because my apps have more new users at now.

**Comment by horrendo** [comment] 2016-05-23 05:07
Paul,

Is this the official point of tracking for this issue?  I want to ensure I don't miss the "this has been fixed" notice.

Thanks.

**Comment by mbg1** [comment] 2016-05-23 15:28
We will post to this thread when the issue has been fixed.

**Comment by lduparc** [comment] 2016-05-25 17:12
Have we the ability to embed the libraries in order to work offline, without download requirement waiting for the fix or use an older version of android vision which still work ?

This issue has a an impact on our business apps. We need a temporary solution.

Thanks.

**Comment by tafayor** [comment] 2016-05-25 20:34
The real question here is that will you disable the api whenever there is an issue like this one in the future ? if so then it's not reliable at all and it would be better to avoid using it,  since it will break our apps and make us lose our users and get bad ratings.

**Comment by horrendo** [comment] 2016-05-26 07:22
If the 'serious problem' exists for users that successfully downloaded the face/barcode detection libraries, what are the implications for them?
If they are ok, why can't the Android-Vision team revert the problematic library so the the old, 'ok' version is available?

The lack of transparency here, and the cavalier attitude Google is taking towards developers is disappointing. There is nothing on the [Mobile Vision](https://developers.google.com/vision/) site that refers to the current problem. The only reference I could find is in the "Highlights" of the Google play services 9.0 release. Really???

What are developers with an existing Play Store app that depends on this functionality supposed to do? Put out some comment saying "Please don't rate me down, it's not my fault. Honest.". Or should they pull the app from the store to prevent bad reviews?

How about trying to see this problem from the developers perspective??

Thanks.

**Comment by vietnt134** [comment] 2016-05-26 07:54
Please have a fix quickly...I can't wait no longer...can you please fix this at the end of this week?

**Comment by mbg1** [comment] 2016-05-26 14:34
We're taking this very seriously and are putting in place mechanisms to prevent and/or rollback should an issue of this magnitude occur in the future.  We will share more details when we can.

**Comment by chakuze** [comment] 2016-05-29 16:35
Is it possible to copy the downloaded files to new devices? As a workaround for testing purpose. If yes, where are the downloaded files located?

**Comment by neoranga55** [comment] 2016-06-01 09:32
We developed a set of features based on this recommended API for barcode scanning and we are about to release it, but we just realized none of our users will be able to use the new features thanks to this bug.
This is a really bad trusting problem with Play Services APIs

**Comment by divyeshjindal** [comment] 2016-06-01 09:58
when will this problem get a fix? Its really a hard time.

**Comment by knyttl** [comment] 2016-06-06 14:11
Well this just started killing our company. We abandoned ZXing for this API and now we heavily rely on it. Is there some kind of workaround to force the device to think that the device already had "installed apps that use mobile vision"?

**Comment by davidtcdeveloper** [comment] 2016-06-06 15:21
This situation is generating big problems here. Is there any status?

**Comment by vietnt134** [comment] 2016-06-07 04:38
Any news? have been 2 weeks already....

**Comment by StefanoFrazzetto** [comment] 2016-06-07 11:09
They will post an update once the problem will be solved. It's useless to keep asking the same question over and over.

**Comment by davidtcdeveloper** [comment] 2016-06-07 11:44
I am sorry if I am being annoying. The problem is that I just don't know what to do.
Is there any other place to check the release schedule? Should I just change my qr code library to another one? 
My app deppends on mobile vision, users are complaining and our app rating is falling.
What should I do?

**Comment by felipeleusin** [comment] 2016-06-07 12:38
Given the fact tha Google disabled the library without further notice or even providing an option, yeah I kinda expected them to do more than this.

@davidtcdeveloper what features are you using? Facial detection or just barcode?

**Comment by knyttl** [comment] 2016-06-07 12:40
What scares me is that they can disable it any time they want in future?

**Comment by davidtcdeveloper** [comment] 2016-06-07 12:43
@felipeleusin using qr code scan only.

**Comment by randallkn** [comment] 2016-06-07 12:46
I don't know about QR libraries, but my company is switching to OpenCV for face detection.

**Comment by felipeleusin** [comment] 2016-06-07 12:49
Yeah, if you need facial detection I recommend going to OpenCV. If it's just barcode I recommend going with QR Codes and https://github.com/dm77/barcodescanner that has decent results. It doesn't have the same features (multitracker) as MobileVision but it works.

**Comment by marlove** [comment] 2016-06-07 12:52
My advice is to remove the dependency from the Mobile Vision API. I solved the problem (for QR code scanning) using ZXing. Only the core library is needed (i.e. compile 'com.google.zxing:core:3.2.0') and the outcome is accurate and reliable.

**Comment by chakuze** [comment] 2016-06-07 16:35
@marlove is it possible to real-time scan multiple barcode using ZXing? If yes, how to implement that?

**Comment by horrendo** [comment] 2016-06-08 00:26
Whilst it may be pointless to ask the same question over and over again, it is a reflection on the disappointing lack of feedback or direction from the google developers.

This issue is now 3 weeks old and there has been nothing of substance from the google team in that time.  Developers are likely reluctant to refactor their code given that the fix could (in theory) be released 'tomorrow'.  They did say they "expect it will take several weeks to test it thoroughly".  Well, it has been "several" weeks, although the definition of "several" is somewhat ambiguous.

If the google devs were to come out and say they were targeting a specific date for release, those of us affected could make a judgement call on what action to take.  You would think that using a google "supported" library (and we now have to take that "support" with a grain of salt) is always the preferred path.  None of us could have predicted this unprecedented fiasco.

The google devs have said they "take this very seriously" but clearly that doesn't extend to keeping the affected developers informed.  Doesn't seem serious from where I'm sitting.

Imagine the uproar if this had happened with one of the other services provided in the Google Play service libraries - e.g. the maps api.

**Comment by theusualcoder** [comment] 2016-06-08 01:18
Adding my voice to this issue.  I understand the frustration of others but since I don't have a breaking app on play I just want to know if I should continue development or pick another library. Communication is key here. Please let us know when we should be expecting a fix.

**Comment by divyeshjindal** [comment] 2016-06-08 04:37
Face Detection is now working on our :)

**Comment by decubate** [comment] 2016-06-08 08:03
@divyeshjindal Using the Google Vision APIs? On a phone that hasn't downloaded the required libraries previously?

**Comment by divyeshjindal** [comment] 2016-06-08 08:08
yes...i tried face detection a week ago on some devices but it wasn't working but now its working fine

**Comment by knyttl** [comment] 2016-06-08 08:20
Barcode scanning still does not work.

**Comment by ChigorinJunior** [comment] 2016-06-08 10:02
It seams that barcode scanning works now! :) I've just tried it in my app.

**Comment by Alessandro994** [comment] 2016-06-08 10:05
Also the face/eyes detection is now working again.

**Comment by horrendo** [comment] 2016-06-08 10:49
@ChigorinJunior  Barcode detection doesn't seem to be working for me. I see this in my logcat output:

`06-08 20:45:01.850 20472-20472/x.x.x.x I/Vision: Requesting barcode detector download.`

But nothing after that.  What do you see?

**Comment by emreozer** [comment] 2016-06-08 11:05
@knyttl you can try multi-tracker sample. Barcode detector works in my app with multi-tracker.

**Comment by decubate** [comment] 2016-06-08 13:15
@emreozer @divyeshjindal @ChigorinJunior : What version of Google play services is installed on the device? I'm still not able to scan barcodes on a new device with 9.0.83. Same issue as before.

**Comment by sjaschke** [comment] 2016-06-08 13:23
@decubate: works today suddenly on my device without any (visible) update neither play services nor barcode sample app
pay-services: 9.0.83 (446-121911109)

**Comment by emreozer** [comment] 2016-06-08 13:30
@decubate I used 9.0.2 version of mobile vision api and all device has latest google play services library in the market. I understood that it works by trying following scenario.;

1. Remove all updates of google play services from device.
2. Install multi detector sample with using 9.0.2.
3. Open sample and wait until Google Play Service Update dialog is shown
4. Update google play services library from market.
5. Try again to read the QR code.

**Comment by divyeshjindal** [comment] 2016-06-08 13:31
@decubate  i am using 9.0.0 version

**Comment by decubate** [comment] 2016-06-08 13:33
Actually, it started working for us now as well. Strange. But I'm not complaining! :)

**Comment by emreozer** [comment] 2016-06-08 13:44
@decubate could you try my answer with problematic phone please?

**Comment by Hcidder** [comment] 2016-06-08 19:19
@emreozer I tried your Method an it worked! On my Phone the Barcodereader didn´t work even after all the statements that it suddenly worked without update or anything.
But after following the steps you privided it stopped showing the error "Barcode dependencies not yet available" an just read the Barcode.....

Still a big nuisance if i have to Install the app in that manner but thanks for providing a workaround for further testing!!

**Comment by ayushindin** [comment] 2016-06-09 20:35
@emreozer Workaround doesn't work with Nexus 6P:-((((((

**Comment by horrendo** [comment] 2016-06-09 20:57
Until a user can download an app using the Mobile Vision API's from the store and it 'just works', this is still a serious problem.

Come on Google team. How about an update?

**Comment by achint-s** [comment] 2016-06-09 22:47
None of the workarounds mentioned work for me - our app is supported on hundreds of handsets - and heavily relies on barcode scanning. This is a mess.

Can we have an urgent update?

**Comment by manojkumarsmks** [comment] 2016-06-09 23:04
@decubate  what did you change or do ??I tried few things mentioned. didn't work for me.

**Comment by knyttl** [comment] 2016-06-10 08:03
This needs to work out of the box from the playstore.

**Comment by decubate** [comment] 2016-06-10 11:06
@manojkumarsmks I'm sorry, I can't really retrace my steps to figure out what I did to get the native libraries to download. :/ I would regard this problem as still unfixed until the Google devs issue a statement saying otherwise.

**Comment by mbg1** [comment] 2016-06-10 19:36
We are in the process of rolling out a fix.  We expect this process to take a couple weeks during which time some phones will have the fix while others will not.  We will message again when the rollout is complete.  No update to your applications will be required for the APIs to be restored; users that have received the updated Play Services will have it restored automatically.

**Comment by ggirard07** [comment] 2016-06-10 21:32
@mbg1 great news.

Could you provide us any version information in order to determine if our dev/test devices are running with the fixed play services?

**Comment by mbg1** [comment] 2016-06-14 14:09
Anything 9.2.XX or above is a fixed version.

**Comment by knyttl** [comment] 2016-06-14 14:21
Is there some release note for the fix? Nothing here: https://developers.google.com/vision/release-notes

Also is there a list of released versions anywhere?

**Comment by achint-s** [comment] 2016-06-14 20:38
Is there a specific set of steps to follow once play services had been updated? Just updated to 9.2.56 on a Nexus 6P on Android N - but it doesn't look like barcode/QR code is scanning.

**Comment by jsvirzi** [comment] 2016-06-18 09:48
When is a fix out? Is this Google's subtle way of telling us to go somewhere else? As in, "you know where you can shove it?"

**Comment by horrendo** [comment] 2016-06-20 18:54
My play services has just today updated to 9.2.56 and reading barcodes is still not working. Exactly the same symptoms. I get:

`I/Vision: Requesting barcode detector download.`

But nothing after.

WTF Google ?!?!?!?

**Comment by maorc1981** [comment] 2016-06-21 06:16
I also upgraded to version 9.2.56 and still **not working**.

In "Google Settings" => "Chimera Modules", I see the following modules marked as F (failed???):
- ads.dynamite
- cast.framework.dynam
- crash
- firebase_database
- firebasestorage
- googlecertificate
- maps_dynamite
- piccard.dynamite
- signinbutton_dynamite
- tagmanager
- **vision.dynamite**

**Comment by markezine** [comment] 2016-06-22 15:55
Was working with a testing device, now doesn't work with another, and we have another ambiguous ETA from the google team. Can you please give us at least an estimate ETA, something like "will take 2-4 weeks" to get this done?
I have a project with a deadline to deliver, and they won't accept "couple weeks" when they ask "how much our project will be delayed?".

**Comment by mbg1** [comment] 2016-06-22 17:02
The Google Play Services update also includes a configuration update as part of the fix for Mobile Vision.  Normally this is updated once every several days, but it will also occur on phone reboot (though this it is throttled, so this is not guaranteed to update the configuration).

While we can't give an exact date on when this will finish rolling out, we expect it to finish soon.

**Comment by markezine** [comment] 2016-06-22 21:32
Is there a way to force install the vision service on a  testing device?

**Comment by roy187** [comment] 2016-06-23 15:58
at least provide us an estimated time tq

**Comment by horrendo** [comment] 2016-06-23 18:52
My devices - both of which were previously failing are now working.

Thanks.

**Comment by knyttl** [comment] 2016-06-24 11:37
@horrendo @maorc1981 How do you define depenedencies in your project?

```
dependencies {
    compile 'com.google.android.gms:play-services-vision:9.2.56'
...
}
```

With this, the new version is still not available.

**Comment by maorc1981** [comment] 2016-06-24 12:43
@knyttl 

`dependencies {
    compile 'com.google.android.gms:play-services-vision:9.0.2'
    ...
}`

**Comment by knyttl** [comment] 2016-06-24 12:48
@maorc1981 Yeah, but that is still 9.0.2, you are saying you upgraded to "I also upgraded to version 9.2.56 and the vision API still not working."

**Comment by maorc1981** [comment] 2016-06-24 13:01
I upgraded the "Google Play Services" app to 9.2.56.

In build.gradle, the highest version possible for gms is 9.0.2 (as much as I understand):
https://developers.google.com/android/guides/releases

I tried putting 9.2.56 in the dependencies but it didn't compile (I'm using IntelliJ IDEA):
> Error:(22, 13) Failed to resolve: com.google.android.gms:play-services-vision:9.2.56
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:/media/maorc/Secondary/Development/PureFunLab/Faces2048/Source/trunk/android/build.gradle">Show in File</a>

What am I doing wrong?

**Comment by knyttl** [comment] 2016-06-27 20:29
@mbg1 I am just wondering: in case you find such a bug next, will you turn the service off like this again?  If it is the case, I think we can all start migrating to something else.

**Comment by maorc1981** [comment] 2016-06-28 20:05
@knyttl  @mbg1  I'm happy to tell that I upgraded to 9.2.0 and issue is solved!

`dependencies {
    compile 'com.google.android.gms:play-services-vision:9.2.0'
    ...
}`

**Comment by carlosmonzon** [comment] 2016-06-28 21:14
after @maorc1981 last post, I tested it, but it still didn't work. I needed to force update the Play Service apk from the play store, re-start the phone and finally it works 

> @knyttl @mbg1 I'm happy to tell that I upgraded to 9.2.0 and issue is solved!
> dependencies { compile 'com.google.android.gms:play-services-vision:9.2.0' ... }

**Comment by roy187** [comment] 2016-06-29 04:49
@maorc1981  WOW thx finally it works!

**Comment by maorc1981** [comment] 2016-06-29 05:54
So what we have to do is:

- Upgrade Google Play Services to 9.2.56 
- Upgrade the gms dependency to 9.2.0
- Restart phone to get the latest configuration file (not sure it's needed)

**Comment by knyttl** [comment] 2016-06-29 09:12
Okay now it works. Now.

But what happens when Google finds another bug? Will they turn it off again?

**Comment by mbg1** [comment] 2016-06-29 14:52
Mobile Vision operation is restored in Google Play Services v9.2.  Users with the new version will be able to download the required files and make use of application features powered by Mobile Vision. The Google Play Services update also includes a configuration update as part of the fix for Mobile Vision.  Normally this is updated once every several days, but it will also occur on phone reboot (though this it is throttled, so this is not guaranteed to update the configuration).  It is not necessary to upgrade the Google Play Services SDK in your applications.  We still advise developers to call FaceDetector.isOperational() or BarcodeDetector. isOperational() to check for detector readiness and degrade feature operation accordingly since files may not download, e.g. due to insufficient storage.

We apologize to developers and users for the outage.  Because we did not discover the issue until after Google Play Services began rolling out, it was not possible to rollback to a workable state without adversely affecting users and developers in other ways.  We are making internal engineering changes to prevent this from happening again.

**Comment by johntzan** [comment] 2016-06-29 15:56
@mbg1 I am still getting the following errors in my logs: 

I/Vision: Requesting barcode detector download.
and 
W/NativeBarcodeDetectorHandle: Native barcode detector not yet available.  Reverting to no-op detection.

and this is after updating to 9.2.0 and on 9.2.56 play services on device. and restarting the phone a bunch of times. Anything i left out that is needed?

**Comment by hwesley** [comment] 2016-07-01 13:44
I also seem to have an issue on a Samsung device (Galaxy A3 2016, Android 5.1.1). Still getting the Barcode detector not being operational.

Using Google Play Services 9.2.0 in app & on device 9.2.56 (236-124593566)

`W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:6
I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 6
I/Vision: Requesting barcode detector download.
I/Vision: Attempting to open download_details.json in com.google.android.gms.vision
W/Vision: Failed to open download_details.json in com.google.android.gms.vision: android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms.vision
I/Vision: Attempting to open download_details.json in com.google.android.gms.policy_ccocr_vision
W/Vision: Failed to open download_details.json in com.google.android.gms.policy_ccocr_vision: android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms.policy_ccocr_vision
W/Vision: Reading download details from hard-coded Java
W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:6
I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 6`

**Comment by grndvl1** [comment] 2016-07-14 22:57
Getting the same error : with 9.2.1 services and latest on device...Nexus 5

07-14 17:55:43.578 16663-16663/W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
07-14 17:55:43.590 16663-16663/com..android I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:6
07-14 17:55:43.590 16663-16663/com..android I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 6
07-14 17:55:43.596 16663-16663/com..android W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000004/n/armeabi-v7a
07-14 17:55:43.596 16663-16663/com..android W/System: ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000004/n/armeabi
07-14 17:55:43.597 16663-16663/com..android D/ChimeraFileApk: Primary ABI of requesting process is armeabi-v7a
07-14 17:55:43.599 16663-16663/com..android D/ChimeraFileApk: Classloading successful. Optimized code found.
07-14 17:55:43.615 16663-16663/com..android I/Vision: Requesting barcode detector download.
07-14 17:55:43.618 16663-16663/com..android W/NativeBarcodeDetectorHandle: Native barcode detector not yet available.  Reverting to no-op detection.

**Comment by mbg1** [comment] 2016-07-15 20:40
We fully appreciate the effect turning off the model download service had on developers who depend on our service. We have taken concrete technical steps to help prevent this from happening again, including:

We added new tests for downloads, in both correctness and frequency, as well as increased test coverage overall.
We built tools to carefully monitor downloads during Google internal testing.

We intend to have this API available for Android developers and users for the foreseeable future.  As this issue has been addressed in 9.2, we're going to close this issue; please keep us informed as we go forward.

**Closed** 2016-07-15 21:11 UTC

**Comment by TLAntonino** [comment] 2016-09-16 13:32
Why it is close, I tried barcode example on a Galaxy Tab and does not work, instead on a chinese tablet works correctly, both with the version  9.4.52...

**Comment by topazas** [comment] 2016-10-04 21:21
Same here version 9.6.+  on Samsung S0
Shame Google...really...

**Comment by pchx** [comment] 2016-10-04 21:38
Library and model downloads were restored as of the [Play Services 9.2 release](https://developers.google.com/vision/release-notes#google_play_services_92). There are other reasons the Mobile Vision APIs may appear not to be working for you, however, they are not due to this particular issue and that is why it is marked as closed.

If you are having trouble with the API, please file a separate bug report and include as much detail as you can. This includes the device type,Play Services version, whether Detector.isOperational() is returning true or not, stack traces, etc.
