### ISSUE TITLE
Native crash in libbarhopper.so for Android 8.1+

### ISSUE THREAD

**Issue by nitheeshkpai** [googlesamples/android-vision#392] opened 2018-11-13 09:56 UTC
Hi guys,

Getting the following native crash for Android 8.1+ devices (I use App bundles): 

backtrace from Play Console:
  #00  pc 000000000001bf44  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
  #01  pc 0000000000011160  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
  #02  pc 0000000000005bd0  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
  #03  pc 0000000000007674  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
  #04  pc 0000000000003624  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
  #05  pc 0000000000004c8c  /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
  #06  pc 0000000000000d58  /data/user_de/0/com.google.android.gms/app_chimera/m/00000009/oat/arm64/DynamiteModulesA.odex

Reporting to let you guys know if you already aren't.

**Comment by pchx** [comment] 2018-11-13 15:41
Thanks, we're aware of this one.

Duplicate of #351.

**Closed by pchx** 2018-11-13 15:41 UTC
