### ISSUE TITLE
Cannot recognise some CODE_39 barcodes

### ISSUE THREAD

**Issue by DeadMeatGF** [googlesamples/android-vision#59] opened 2016-01-07 10:11 UTC
Using the barcode capture example almost everything is working as expected, however we have a range of ID stickers with a 5-digit CODE_39 barcode. The app cannot recognise these as a barcode,
It does recognise other CODE_39 (and other format) barcodes OK, and ZXing recognises the stickers as normal.
![screenshot_2016-01-07-10-06-32](https://cloud.githubusercontent.com/assets/11074763/12167944/0bbbc96a-b527-11e5-98e7-97726e839791.png)
![screenshot_2016-01-07-10-06-58](https://cloud.githubusercontent.com/assets/11074763/12167945/0bbbfdd6-b527-11e5-9d27-6a763e0e897e.png)

**Comment by pchx** [comment] 2016-01-07 15:26
Duplicate of issue #12 -- the API only returns results for 1D barcodes with 6 or more digits.

**Closed** 2017-08-03 18:54 UTC
Labels: Barcode, duplicate
