### ISSUE TITLE
Crash on Samsung S7 Edge 

### ISSUE THREAD

**Issue by rgdixit** [googlesamples/android-vision#276] opened 2017-10-24 09:41 UTC
I have been getting consistent app crashes upon running the app on S7 edge. 
The crash log seems something like
10-24 13:35:36.331 24079-24079/com.test.myApp A/native: timer.cc:38 Check failed: x >= 1 (0 vs. 1) 
10-24 13:35:36.331 24079-24079/com.test.myApp A/native: terminating.
10-24 13:35:36.332 24079-24079/com.test.myApp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 24079 (est.myApp)
                                                            
                                                            [ 10-24 13:35:36.333  3095: 3095 W/         ]
                                                            debuggerd: handling request: pid=24079 uid=10258 gid=10258 tid=24079
10-24 13:35:36.353 3245-3245/? E/audit: type=1400 audit(1508832336.343:1692): avc:  denied  { search } for  pid=29331 comm="debuggerd64" name="com.google.android.gms" dev="dm-1" ino=262375 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.0_0006
10-24 13:35:36.353 3245-3245/? E/audit: type=1300 audit(1508832336.343:1692): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=744428b480 a2=0 a3=0 items=0 ppid=3095 pid=29331 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="debuggerd64" exe="/system/bin/debuggerd64" subj=u:r:debuggerd:s0 key=(null)
10-24 13:35:36.353 3245-3245/? E/audit: type=1327 audit(1508832336.343:1692): proctitle="/system/bin/debuggerd64"
10-24 13:35:36.353 3245-3245/? E/audit: type=1320 audit(1508832336.343:1692): 
10-24 13:35:36.354 3245-3245/? E/audit: type=1400 audit(1508832336.343:1693): avc:  denied  { search } for  pid=29331 comm="debuggerd64" name="com.google.android.gms" dev="dm-1" ino=721083 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.0_0006
10-24 13:35:36.354 3245-3245/? E/audit: type=1300 audit(1508832336.343:1693): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=7444226380 a2=0 a3=0 items=0 ppid=3095 pid=29331 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="debuggerd64" exe="/system/bin/debuggerd64" subj=u:r:debuggerd:s0 key=(null)
10-24 13:35:36.355 3245-3245/? E/audit: type=1327 audit(1508832336.343:1693): proctitle="/system/bin/debuggerd64"
10-24 13:35:36.355 3245-3245/? E/audit: type=1320 audit(1508832336.343:1693): 
10-24 13:35:36.360 3245-3245/? E/audit: type=1400 audit(1508832336.343:1694): avc:  denied  { search } for  pid=29331 comm="debuggerd64" name="com.google.android.gms" dev="dm-1" ino=721083 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.0_0006
10-24 13:35:36.360 3245-3245/? E/audit: type=1300 audit(1508832336.343:1694): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=7444226000 a2=0 a3=0 items=0 ppid=3095 pid=29331 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="debuggerd64" exe="/system/bin/debuggerd64" subj=u:r:debuggerd:s0 key=(null)
10-24 13:35:36.360 3245-3245/? E/audit: type=1327 audit(1508832336.343:1694): proctitle="/system/bin/debuggerd64"
10-24 13:35:36.360 3245-3245/? E/audit: type=1320 audit(1508832336.343:1694): 
10-24 13:35:36.462 29331-29331/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-24 13:35:36.463 29331-29331/? A/DEBUG: Build fingerprint: 'samsung/heroltexx/herolte:7.0/NRD90M/G930FXXS1DQGB:user/release-keys'
10-24 13:35:36.463 29331-29331/? A/DEBUG: Revision: '8'
10-24 13:35:36.463 29331-29331/? A/DEBUG: ABI: 'arm64'
10-24 13:35:36.463 29331-29331/? A/DEBUG: pid: 24079, tid: 24079, name: est.myApp  >>> com.test.myApp <<<
10-24 13:35:36.463 29331-29331/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
10-24 13:35:36.471 29331-29331/? A/DEBUG: Abort message: 'timer.cc:38 Check failed: x >= 1 (0 vs. 1) 
                                          '
10-24 13:35:36.471 29331-29331/? A/DEBUG:     x0   0000000000000000  x1   0000000000005e0f  x2   0000000000000006  x3   0000000000000008
10-24 13:35:36.471 29331-29331/? A/DEBUG:     x4   0000000000000070  x5   0000008000000000  x6   000000783fbe0000  x7   0000000000000000
10-24 13:35:36.471 29331-29331/? A/DEBUG:     x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  ffffffffffffffff
10-24 13:35:36.471 29331-29331/? A/DEBUG:     x12  0000000000000018  x13  0000000000000000  x14  0000000000000000  x15  0013c06e25b979c6
10-24 13:35:36.472 29331-29331/? A/DEBUG:     x16  000000783f1ccee0  x17  000000783f175a28  x18  0000007801e70d3d  x19  000000783fc95b40
10-24 13:35:36.472 29331-29331/? A/DEBUG:     x20  0000000000000006  x21  000000783fc95a98  x22  0000000000000002  x23  0000007801c27830
10-24 13:35:36.472 29331-29331/? A/DEBUG:     x24  00000077ff16c780  x25  0000007801e53460  x26  00000077fea91478  x27  0000007ffb69a118
10-24 13:35:36.472 29331-29331/? A/DEBUG:     x28  0000000000000000  x29  0000007ffb6992a0  x30  000000783f172ebc
10-24 13:35:36.472 29331-29331/? A/DEBUG:     sp   0000007ffb699280  pc   000000783f175a30  pstate 0000000060000000
10-24 13:35:36.475 3245-3245/? E/audit: type=1400 audit(1508832336.463:1695): avc:  denied  { search } for  pid=29331 comm="debuggerd64" name="com.google.android.gms" dev="dm-1" ino=262375 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.0_0006
10-24 13:35:36.475 3245-3245/? E/audit: type=1300 audit(1508832336.463:1695): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=744428b480 a2=0 a3=0 items=0 ppid=3095 pid=29331 auid=4294967295 uid=1045 gid=1045 euid=1045 suid=1045 fsuid=1045 egid=1045 sgid=1045 fsgid=1045 tty=(none) ses=4294967295 comm="debuggerd64" exe="/system/bin/debuggerd64" subj=u:r:debuggerd:s0 key=(null)
10-24 13:35:36.475 3245-3245/? E/audit: type=1327 audit(1508832336.463:1695): proctitle="/system/bin/debuggerd64"
10-24 13:35:36.475 3245-3245/? E/audit: type=1320 audit(1508832336.463:1695): 
10-24 13:35:36.489 29331-29331/? A/DEBUG: backtrace:
10-24 13:35:36.489 3245-3245/? E/audit: type=1400 audit(1508832336.473:1696): avc:  denied  { search } for  pid=29331 comm="debuggerd64" name="com.google.android.gms" dev="dm-1" ino=721083 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SECMOBILE_7.0_0006
10-24 13:35:36.489 3245-3245/? E/audit: type=1300 audit(1508832336.473:1696): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=7444226380 a2=0 a3=0 items=0 ppid=3095 pid=29331 auid=4294967295 uid=1045 gid=1045 euid=1045 suid=1045 fsuid=1045 egid=1045 sgid=1045 fsgid=1045 tty=(none) ses=4294967295 comm="debuggerd64" exe="/system/bin/debuggerd64" subj=u:r:debuggerd:s0 key=(null)
10-24 13:35:36.489 29331-29331/? A/DEBUG:     #00 pc 000000000006ca30  /system/lib64/libc.so (tgkill+8)
10-24 13:35:36.489 3245-3245/? E/audit: type=1327 audit(1508832336.473:1696): proctitle="/system/bin/debuggerd64"
10-24 13:35:36.489 29331-29331/? A/DEBUG:     #01 pc 0000000000069eb8  /system/lib64/libc.so (pthread_kill+64)
10-24 13:35:36.489 3245-3245/? E/audit: type=1320 audit(1508832336.473:1696): 
10-24 13:35:36.489 29331-29331/? A/DEBUG:     #02 pc 0000000000024198  /system/lib64/libc.so (raise+24)
10-24 13:35:36.489 29331-29331/? A/DEBUG:     #03 pc 000000000001c9b0  /system/lib64/libc.so (abort+52)
10-24 13:35:36.489 29331-29331/? A/DEBUG:     #04 pc 00000000004750d0  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.489 29331-29331/? A/DEBUG:     #05 pc 0000000000475770  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.489 29331-29331/? A/DEBUG:     #06 pc 0000000000475814  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #07 pc 0000000000474830  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #08 pc 000000000026cee4  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #09 pc 0000000000271190  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #10 pc 0000000000065794  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #11 pc 0000000000065488  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #12 pc 000000000027caf4  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #13 pc 0000000000280274  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #14 pc 0000000000067c84  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #15 pc 0000000000067f64  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #16 pc 0000000000063dec  /data/data/com.google.android.gms/app_vision/ocr/libs/arm64-v8a/libocr.so
10-24 13:35:36.490 29331-29331/? A/DEBUG:     #17 pc 0000000000387f00  /data/user_de/0/com.google.android.gms/app_chimera/m/00000034/oat/arm64/DynamiteModulesA_GmsCore_prodmnc_xxhdpi_release.odex (offset 0x4e7000)
10-24 13:35:40.738 3245-3245/? E/audit: type=1701 audit(1508832340.723:1697): auid=4294967295 uid=10258 gid=10258 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=24079 comm="ruecaller.debug" exe="/system/bin/app_process64" sig=6
10-24 13:35:40.767 3111-3111/? E/lowmemorykiller: Error writing /proc/24079/oom_score_adj; errno=22`

**Comment by liuyl** [comment] 2017-10-24 14:55
This is a duplicate of #269

**Closed** 2017-10-24 14:56 UTC

**Comment by rgdixit** [comment] 2017-10-24 16:10
thanks for the update!
